### PR TITLE
update: updated country.yml with latest

### PR DESCRIPTION
**Pull request by devkumarvdb**
Heroku Update fix.

Updated countries.yml because we cannot perform on update.

### CODE REVIEW

**Comment by inderps** [comment]
@devkumarvdb Can you please update "Republic of Lithuania" to "Lithuania" as well?

**Comment by inderps** [comment]
@loureirorg is this ever going to be merged?

**Comment by devkumarvdb** [comment]
> @devkumarvdb Can you please update "Republic of Lithuania" to "Lithuania" as well?

Sure will

**Comment by devkumarvdb** [comment]
> @devkumarvdb Can you please update "Republic of Lithuania" to "Lithuania" as well?

Sure I will check on it.

**Comment by loureirorg** [comment]
@inderps I understand it can be frustrating to have a country name in a different way than is expected or known. 

But as this library is just a wrapper to the MaxMind database, anything written to `country.yml` file is gonna be lost on an update.

If you want to fix a name, the best way is to use `db/countries-lookup.yml`:

```yaml
# db/countries-lookup.yml
LT: "Lithuania"
```

**Comment by loureirorg** [comment]
@devkumarvdb Thanks for spending some time updating the countries list.

I will merge your PR but be aware that I have plans to create a GitHub action to automatically update this file from time to time using `CS.update` command. This means any change that is not in sync with MaxMind will be lost.

**Comment by devkumarvdb** [comment]
@loureirorg No worries the update was done using CS.update only.

**Pull request merged**
